---
- hosts: all
  vars:
    script_name: hola_mundo.py
    script_url: https://raw.githubusercontent.com/jaandro98/ansible-flink/master/hola_mundo.py
    script_path: /home/centos/
  tasks:
    - name: Download python script from Github
      get_url: 
        url: "{{ script_url }}"
        dest: /home/centos/
        mode: 0644
    - name: Run hello world python script
      command: "python {{ script_path + script_name }}"
      register: output
    - debug: var=output.stdout_lines
    - name: Remove python script after execution
      file:
        path: "{{ script_path + script_name }}"
        state: absent
