---
- hosts: all
  tasks:
    - name: Download python script from Github
      get_url:
        url: https://raw.githubusercontent.com/jaandro98/ansible-flink/master/hola_mundo.py
        dest: /home/centos/
        mode: 0644
    - name: Run hello world python script
      command: python /home/centos/hola_mundo.py
      register: output
    - debug: var=output.stdout_lines
