---
- hosts: localhost
  connection: local
  vars:
    script_zip: https://github.com/jaandro98/ansible-flink/raw/master/python.tar.gz
    zip_name: python.tar.gz
    local_path: /home/alejandro/
  tasks:
    - name: Download python zip script from Github
      get_url: 
        url: "{{ script_zip }}"
        dest: "{{ local_path }}"
        mode: 0644
    - name: unzip python script
      unarchive:
        src: "{{ local_path + zip_name }}"
        dest: "{{ local_path }}"
- hosts: 192.168.1.50
  vars:
    script_name: hola_mundo.py
    script_path: /home/centos/
    zip_name: python.tar.gz
    local_path: /home/alejandro/
  tasks:
    - name: Run hello world python script
      script: "{{ local_path + script_name }}"
      register: output
    - debug: var=output.stdout_lines
    - name: Remove python script after execution
      file:
        path: "{{ script_path + script_name }}"
        state: absent
    - name: Remove python tar after execution
      file:
        path: "{{ script_path + zip_name }}"
        state: absent
    
