---
- hosts: local
  connection: local
  vars_files:
    - "../defaults/main.yml"
  vars:
    #config_path: https://raw.githubusercontent.com/jaandro98/ansible-flink/master/files/config.yml
    #jar_path: https://github.com/jaandro98/ansible-flink/raw/master/files/httpclient-4.5.2.jar
    #local_path: /home/alejandro/
  tasks:
    - name: Download config tar gz
      get_url: 
        url: "{{ config_path }}"
        dest: "{{ local_path }}"
        mode: 0644
    - name: Download jar file
      get_url: 
        url: "{{ jar_path }}"
        dest: "{{ local_path }}"
        mode: 0644
    - name: Unzip config yaml file
      unarchive:
        src: "{{ local_path + zip_config }}"
        dest: "{{ local_path }}"
      
- hosts: remote
  vars_files:
    - "../defaults/main.yml"
  vars:
    #local_path: /home/alejandro/
    #dest_path: /home/centos/
    #config_name: config.yml
    #jar_name: httpclient-4.5.2.jar
  tasks:
    - name: Copy config file to remote
      copy:
        src: "{{ local_path + config_name }}"
        dest: "{{ dest_path }}"
        mode: 0644
    - name: Copy jar file to remote
      copy:
        src: "{{ local_path + jar_name }}"
        dest: "{{ dest_path }}"
        mode: 0644

