---
- hosts: local
  connection: local
  vars:
    #config_path: https://raw.githubusercontent.com/jaandro98/ansible-flink/master/files/config.yml
    #jar_path: https://github.com/jaandro98/ansible-flink/raw/master/files/httpclient-4.5.2.jar
    #local_path: /home/alejandro/
  tasks:
    - name: Download config file
      get_url: 
        url: "{{ hostvars['localhost']['config_path'] }}"
        dest: "{{ hostvars['localhost']['local_path'] }}"
        mode: 0644
    - name: Download jar file
      get_url: 
        url: "{{ hostvars['localhost']['jar_path'] }}"
        dest: "{{ hostvars['localhost']['local_path'] }}"
        mode: 0644
    - name: Unzip config yaml file
      unarchive:
        src: "{{ hostvars['localhost']['local_path'] + hostvars['localhost']['zip_config'] }}"
        dest: "{{ hostvars['localhost']['local_path'] }}"
      
- hosts: remote
  vars:
    #local_path: /home/alejandro/
    #dest_path: /home/centos/
    #config_name: config.yml
    #jar_name: httpclient-4.5.2.jar
  tasks:
    - name: Copy config file to remote
      copy:
        src: "{{ hostvars['localhost']['local_path'] + hostvars['192.168.1.62']['config_name'] }}"
        dest: "{{ hostvars['192.168.1.62']['dest_path'] }}"
        mode: 0644
    - name: Copy jar file to remote
      copy:
        src: "{{ hostvars['localhost']['local_path'] + hostvars['192.168.1.62']['jar_name'] }}"
        dest: "{{ hostvars['192.168.1.62']['dest_path'] }}"
        mode: 0644

